name: webhook

on:
  push:

jobs:
  verify-prettier:
    if: contains('refs/heads/main', github.ref)
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Prettier check
        run: npm run verify:prettier
